title: "Who hurt you...."?? "My Own expectations".
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 You can update description in update blog details page.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://cyobb.com/violetgirl" # the base hostname & protocol for your site
twitter_username: jekyllrb

markdown: kramdown

name: "Who hurt you...."?? "My Own expectations".

date: 2017-06-10 22:03:28 +0000
permalink: /:year/:month/:day/:title

logo: false
paginate: 10
domain_name: http://cyobb.com/violetgirl/
google_analytics: UA-31XXXXXX-X
gems: [jekyll-paginate]
cover: 
author_image: 
# Details for the RSS feed generator
author:        violetgirl
